name: budget_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Database
  drift: ^2.26.0
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5

  # State Management
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  provider: ^6.1.2

  # DI 
  get_it: ^8.0.3
  injectable: ^2.5.0

  # UI
  syncfusion_flutter_charts: ^29.1.33
  carousel_slider: ^5.0.0

  # Other
  equatable: ^2.0.7  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation
  drift_dev: ^2.26.0
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf
        - asset: assets/fonts/open_sans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/open_sans/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/open_sans/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic



flutter_intl:
  enabled: true
  arb_dir: lib/src/core/localization/l10n
  output_dir: lib/src/core/localization/generated
