name: budget_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  build_runner: ^2.4.12
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf
        - asset: assets/fonts/open_sans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/open_sans/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/open_sans/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic



flutter_intl:
  enabled: true
  arb_dir: lib/src/core/localization/l10n
  output_dir: lib/src/core/localization/generated
